// const userInfo = {
//   "data": {
//     "xx": 2,
//     "allowModifyLoginName": 1,
//     "reghref": "",
//     "openflag": 2,
//     "emailbindflag": 2,
//     "sign": "不羡鸳鸯不羡仙，一行代码调半天",
//     "fdvalidtype": 1,
//     "remark": "",
//     "thirdtype": 5,
//     "secretProtectionBindFlag": 2,
//     "freezeLogin": 0,
//     "tiono": "cod_60043919",
//     "nick": "TY-MasterJ-前端",
//     "updPwdtime": "1675995973000",
//     "thirdstatus": 1,
//     "realnameflag": 2,
//     "registertype": 1,
//     "mg": false,
//     "id": 178624,
//     "email": "",
//     "thirdbindflag": 2,
//     "createtime": "1640312403000",
//     "msgforbiddenflag": 2,
//     "level": 1,
//     "loginname": "jstymasterj",
//     "userSetting": {
//       "friendapplygroup": 1,
//       "searchbyname": 1,
//       "showtel": 0,
//       "invitejoingroup": 1,
//       "friendapplyfriend": 1,
//       "groupflowdownload": 1,
//       "uid": 178624,
//       "cancelTimeConfig": [7, 90, 180, 365],
//       "voip": 1,
//       "lang": 0,
//       "friendapplyvisitingcard": 1,
//       "friendapplyforward": 0,
//       "friendapplysearch": 1,
//       "invitejoinchannel": 1,
//       "autoDeletion": 0,
//       "createtime": "1640312583000",
//       "canceltime": 180,
//       "showlastonlinetime": 1,
//       "groupwifidownload": 0,
//       "channelwifidownload": 0,
//       "chatwifidownload": 0,
//       "chatflowdownload": 1,
//       "searchbytel": 1,
//       "searchbyloginname": 1,
//       "friendapplyqrcode": 1,
//       "sendmsg": 1,
//       "needchangepwd": 0,
//       "updatetime": "1680943480000",
//       "channelflowdownload": 1
//     },
//     "updLoginNameExt": 2,
//     "phonebindflag": 1,
//     "avatar": "user/avatar/1666312388766584832_sm.jpg",
//     "avatar": "user/avatar/1666369614038421504.gif",
//     "unfreeze": 0,
//     "updloginname": 2,
//     "msgremindflag": 1,
//     "avatarbig": "user/avatar/1666312388766584832.jpg",
//     "delsign": -1,
//     "paypwdflag": 2,
//     "searchflag": 1,
//     "updatetime": "1686115423000",
//     "initialAvatar": false,
//     "invFlag": false,
//     "status": 1
//   }, "state": "ok", "ok": true
// }


var reg = /\/\/.*\//